	CREATE SEQUENCE  "BL_USERAPPLICATION_SEQ" MINVALUE 1 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;

	CREATE TABLE "BL_USERAPPLICATION" (
		"USERAPPLICATIONID" integer,
		"USERID" integer NOT NULL,
		"APPLICATIONID" integer NOT NULL,
		CONSTRAINT bl_userApplication_pkey PRIMARY KEY ("USERAPPLICATIONID"),
		CONSTRAINT fk_userApplication_userId FOREIGN KEY ("USERID") REFERENCES bl_User("USERID"),
		CONSTRAINT fk_userApplication_AppId FOREIGN KEY ("APPLICATIONID") REFERENCES bl_Application("APPLICATIONID")
	);
	
	ALTER TABLE "bl_User" ADD COLUMN "APIKEY" VARCHAR2(100) NULL;
	