--Drop statements will throw errors if sequences/tables don't currently exist, but script will continue so just ignore them.

--Drop sequences

	DROP SEQUENCE "BL_ENTRY_SEQ";
	DROP SEQUENCE "BL_APPLICATION_SEQ";
	DROP SEQUENCE "BL_HOST_SEQ";
	DROP SEQUENCE "BL_SEVERITY_SEQ";
	DROP SEQUENCE "BL_SOURCE_SEQ";
	DROP SEQUENCE "BL_USER_SEQ";
	DROP SEQUENCE "BL_EXTENSION_SEQ";
	DROP SEQUENCE "BL_EXTENSIONLOG_SEQ";
	DROP SEQUENCE "BL_USERAPPLICATION_SEQ";

--Drop tables (and their integrity constraints)

	DROP TABLE "BL_ENTRY" cascade constraints;
	DROP TABLE "BL_APPLICATION" cascade constraints;
	DROP TABLE "BL_HOST" cascade constraints;
	DROP TABLE "BL_SEVERITY" cascade constraints;
	DROP TABLE "BL_SOURCE" cascade constraints;
	DROP TABLE "BL_USER" cascade constraints;
	DROP TABLE "BL_EXTENSION" cascade constraints;
	DROP TABLE "BL_EXTENSIONLOG" cascade constraints;
	DROP TABLE "BL_USERAPPLICATION" cascade constraints;

--Create sequences (sequences are Oracle's version of autoincrementing integers for unique IDs)

	CREATE SEQUENCE  "BL_ENTRY_SEQ" MINVALUE 1 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
	CREATE SEQUENCE  "BL_APPLICATION_SEQ" MINVALUE 1 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
	CREATE SEQUENCE  "BL_HOST_SEQ" MINVALUE 1 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
	CREATE SEQUENCE  "BL_SEVERITY_SEQ" MINVALUE 1 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
	CREATE SEQUENCE  "BL_SOURCE_SEQ" MINVALUE 1 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
	CREATE SEQUENCE  "BL_EXTENSION_SEQ" MINVALUE 1 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
	CREATE SEQUENCE  "BL_EXTENSIONLOG_SEQ" MINVALUE 1 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
	CREATE SEQUENCE  "BL_USERAPPLICATION_SEQ" MINVALUE 1 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
	
	--Starting with 2 as will be manually inserting initial admin account
	CREATE SEQUENCE  "BL_USER_SEQ" MINVALUE 1 INCREMENT BY 1 START WITH 2 CACHE 20 NOORDER  NOCYCLE;
	
--Create tables

	CREATE TABLE "BL_APPLICATION" (
		"APPLICATIONID" integer,
		"CODE" varchar2(100) NOT NULL,
		"NAME" varchar2(250) NOT NULL,
		CONSTRAINT bl_Application_pkey PRIMARY KEY ("APPLICATIONID"),
		CONSTRAINT bl_Application_Code_unique UNIQUE ("CODE")
	);
	
	CREATE TABLE "BL_HOST" (
		"HOSTID" integer,
		"HOSTNAME"  varchar2(255) NOT NULL,
		CONSTRAINT bl_Host_pkey PRIMARY KEY ("HOSTID")
	);
	
	
	CREATE TABLE "BL_SEVERITY" (
		"SEVERITYID" integer,
		"NAME" varchar2(250) NOT NULL,
		"CODE" varchar2(10) NOT NULL,
		CONSTRAINT bl_Severity_pkey PRIMARY KEY ("SEVERITYID")
	);
	
	CREATE TABLE "BL_SOURCE" (
		"SOURCEID" integer,
		"NAME" varchar2(255) NOT NULL,
		CONSTRAINT bl_Source_pkey PRIMARY KEY ("SOURCEID")
	);
	
	CREATE TABLE "BL_ENTRY" (
		"ENTRYID" integer,
		"MYDATETIME" Timestamp NOT NULL,
		"MESSAGE" varchar2(500) NOT NULL,
		"APPLICATIONID" integer NOT NULL,
		"SOURCEID" integer NOT NULL,
		"SEVERITYID" integer NOT NULL,
		"HOSTID" integer NOT NULL,
		"EXCEPTIONMESSAGE" varchar2(500) default NULL,
		"EXCEPTIONDETAILS" CLOB default NULL,
		"CFID" varchar2(255) default NULL,
		"CFTOKEN" varchar2(500) default NULL,
		"USERAGENT" varchar2(500) default NULL,
		"TEMPLATEPATH" varchar2(500) default NULL,
		"HTMLREPORT" CLOB default NULL,
		"CREATEDON" Timestamp(6) default CURRENT_TIMESTAMP NOT NULL ENABLE,
		CONSTRAINT bl_Entry_pkey PRIMARY KEY ("ENTRYID"),
		CONSTRAINT fk_Entry_HostId FOREIGN KEY ("HOSTID") REFERENCES bl_Host("HOSTID"),
		CONSTRAINT fk_Entry_SeverityId FOREIGN KEY ("SEVERITYID") REFERENCES bl_Severity("SEVERITYID"),
		CONSTRAINT fk_Entry_SourceId FOREIGN KEY ("SOURCEID") REFERENCES bl_Source("SOURCEID"),
		CONSTRAINT fk_Entry_ApplicationId FOREIGN KEY ("APPLICATIONID") REFERENCES bl_Application("APPLICATIONID")
	);
	
	CREATE TABLE "BL_USER" (
		"USERID" integer,
		"USERNAME" varchar2(255) NOT NULL,
		"PASSWORD" varchar2(50) NOT NULL,
		"ISADMIN" number(*,0) default 0 NOT NULL ENABLE,
		"EMAIL" varchar2(255) NULL,
		"APIKEY" varchar2(100) NULL,
		CONSTRAINT bl_User_pkey PRIMARY KEY ("USERID")
	);
	
	--Insert initial admin account
	INSERT INTO "BL_USER" (USERID, USERNAME, PASSWORD, ISADMIN) VALUES (1, 'admin', 'admin', 1);
	
	CREATE TABLE "BL_EXTENSION" (
		"EXTENSIONID" integer,
		"NAME" varchar2(255) NOT NULL,
		"TYPE" varchar2(255) NOT NULL,
		"ENABLED" number(*,0) default 0 NOT NULL ENABLE,
		"DESCRIPTION" varchar2(500) NULL,
		"PROPERTIES" CLOB NULL,
		"CREATEDBY" integer NULL,
		"CREATEDON" timestamp(6) default CURRENT_TIMESTAMP NOT NULL ENABLE,
		CONSTRAINT bl_Extension_pkey PRIMARY KEY ("EXTENSIONID")
	);
	
	CREATE TABLE "BL_EXTENSIONLOG" (
		"EXTENSIONLOGID" integer,
		"EXTENSIONID" integer NOT NULL,
		"CREATEDON" timestamp(6) default CURRENT_TIMESTAMP NOT NULL ENABLE,
		"ENTRYID" integer NOT NULL,
		CONSTRAINT bl_ExtensionLog_pkey PRIMARY KEY ("EXTENSIONLOGID")
	);

	CREATE TABLE "BL_USERAPPLICATION" (
		"USERAPPLICATIONID" integer,
		"USERID" integer NOT NULL,
		"APPLICATIONID" integer NOT NULL,
		CONSTRAINT bl_userApplication_pkey PRIMARY KEY ("USERAPPLICATIONID"),
		CONSTRAINT fk_userApplication_userId FOREIGN KEY ("USERID") REFERENCES bl_User("USERID"),
		CONSTRAINT fk_userApplication_ApplicationId FOREIGN KEY ("APPLICATIONID") REFERENCES bl_Application("APPLICATIONID")
	);
	